{% set data = load_setup_py_data() %}

package:
  name: ts-m2gui
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script_env:
    - QT_API=PySide2
    - PYTEST_QT_API=PySide2
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_m2gui = lsst.ts.m2gui.application:run_application

# The 'pytest' always aborts itself on MacOS or Jenkins. Maybe the coexistence
# of PySide2 and PySide5 has the problem when running the tests. Comment this
# test section at this moment.

# test:
#   requires:
#     - {{ cdt('mesa-libgl-devel') }}  # [linux]
#     - {{ cdt('mesa-dri-drivers') }}  # [linux]
#     - {{ cdt('libselinux') }}  # [linux]
#     - {{ cdt('libxdamage') }}  # [linux]
#     - {{ cdt('libxxf86vm') }}  # [linux]
#     - {{ cdt('libxext') }}     # [linux]
#     - ts-conda-build =0.3
#     - ts-idl {{ idl_version }}
#     - pytest-qt
#     - ts-tcpip
#     - ts-m2com
#   source_files:
#     - python
#     - bin
#     - tests
#     - setup.cfg
#     - pyproject.toml
#   commands:
#     - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
    - xorg-libxfixes # [linux]
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - pandas
    - pyside2
    - qasync
    - ts-tcpip
    - ts-m2com
